### ISSUE TITLE
What is f'n "lm.all"?

### ISSUE THREAD

**Issue by the-Zian** [priism-center/ihdp#3]
https://github.com/priism-center/ihdp/blob/807c6a80af851805e638e7c2e9bed1c5354a2174/analysis_old/ihdp.1500.R#L219

Typo?

**Comment by the-Zian** [comment]
Jennifer to look for and send missing functions

**Comment by marcascott** [comment]
do you know her GitHub ID so I can add her?

**Comment by the-Zian** [comment]
@marcascott it's jennifer-hill (jennifer.hill@nyu.edu)
